/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a6313a70-c07d-4562-a45c-f3cdda90b2ac",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZmdKoYORH",
    "aws_user_pools_web_client_id": "43vhss73dmgm9su5nlc9l95v7c",
    "oauth": {}
};


export default awsmobile;
